# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 547e3be1522e2fd442aa9a14f2980672429ed1db41976fe4bfd7918eb44c6e5312d5e9d1bf9f8b09a02bfddde0accc9aeabc7627f8a13feb15a077fbaa8242b1

test:
  secret_key_base: 5372d2c4ef83368d3e8dad4bf22978eb7610e30c5762a43b523f5000ff40bf544bbc6ab7685e35b51463c048a290361ed15fe2b13455eb9260efd2669d142d40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
